# Generated by Django 5.0.6 on 2024-08-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='question_quantity',
            field=models.SmallIntegerField(default=20, verbose_name='Savollar soni'),
        ),
    ]
