# Generated by Django 5.0.6 on 2024-07-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_middle_name', models.CharField(max_length=100)),
                ('student_age', models.PositiveIntegerField()),
                ('father_first_name', models.CharField(max_length=100)),
                ('father_last_name', models.CharField(max_length=100)),
                ('father_middle_name', models.CharField(max_length=100)),
                ('father_age', models.PositiveIntegerField()),
                ('mother_first_name', models.CharField(max_length=100)),
                ('mother_last_name', models.CharField(max_length=100)),
                ('mother_middle_name', models.CharField(max_length=100)),
                ('mother_age', models.PositiveIntegerField()),
                ('student_phone_number', models.CharField(max_length=100)),
                ('father_phone_number', models.CharField(max_length=100)),
                ('mother_phone_number', models.CharField(max_length=100)),
                ('student_address', models.CharField(max_length=1000)),
                ('student_passport_id', models.CharField(blank=True, max_length=100)),
                ('student_passport_serial_number', models.CharField(blank=True, max_length=100)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('student_passport_front', models.ImageField(blank=True, null=True, upload_to='student_passport_front_photos/')),
                ('student_passport_back', models.ImageField(blank=True, null=True, upload_to='student_passport_back_photos/')),
            ],
        ),
    ]
