# Generated by Django 5.0.6 on 2024-07-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_is_available',
            field=models.BooleanField(default=True),
        ),
    ]
