# Generated by Django 5.0.6 on 2024-07-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_student_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='father_first_name',
            new_name='onasi_familiyasi',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='father_last_name',
            new_name='onasi_ismi',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='father_middle_name',
            new_name='onasi_otasi_nomi',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='father_phone_number',
            new_name='onasi_telefon_raqami',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='father_age',
            new_name='onasi_yoshi',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mother_first_name',
            new_name='otasi_familiyasi',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mother_last_name',
            new_name='otasi_ismi',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mother_middle_name',
            new_name='otasi_otasi_nomi',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mother_phone_number',
            new_name='otasi_telefon_raqami',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mother_age',
            new_name='otasi_yoshi',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_first_name',
            new_name='talaba_familiyasi',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_last_name',
            new_name='talaba_ismi',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_address',
            new_name='talaba_manzili',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_is_available',
            new_name='talaba_mavjud',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_middle_name',
            new_name='talaba_otasi_nomi',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_passport_id',
            new_name='talaba_pasport_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_passport_serial_number',
            new_name='talaba_pasport_seriya_raqami',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_phone_number',
            new_name='talaba_telefon_raqami',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_age',
            new_name='talaba_yoshi',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_passport_back',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_passport_front',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_photo',
        ),
        migrations.AddField(
            model_name='student',
            name='talaba_fotosurati',
            field=models.ImageField(blank=True, null=True, upload_to='talaba_fotosuratlari/'),
        ),
        migrations.AddField(
            model_name='student',
            name='talaba_pasport_oldi',
            field=models.ImageField(blank=True, null=True, upload_to='talaba_pasport_oldi_suratlari/'),
        ),
        migrations.AddField(
            model_name='student',
            name='talaba_pasport_orqa',
            field=models.ImageField(blank=True, null=True, upload_to='talaba_pasport_orqa_suratlari/'),
        ),
    ]
