# Generated by Django 5.0.6 on 2024-07-06 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_father_first_name_student_onasi_familiyasi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='talaba_manzili',
            new_name='talaba_yashash_manzili',
        ),
    ]
