# Generated by Django 5.0.6 on 2024-07-06 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_talaba_manzili_student_talaba_yashash_manzili'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Talaba',
        ),
    ]
