# Generated by Django 5.0.6 on 2024-08-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_rename_student_talaba'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talaba',
            options={'verbose_name': 'Talaba', 'verbose_name_plural': 'Talabalar'},
        ),
    ]
