version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your nginx.conf file
      - static_volume:/app/static  # Mount static files for Nginx
      - media_volume:/app/media
    depends_on:
      - web  # Ensure 'web' service starts before 'nginx'

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5432:5432

  web:
    build: .
    command: gunicorn NurliKelajakMaktab.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app  # Mount the entire application directory
      - static_volume:/app/static  # Mount static files for Django
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=NurliKelajakMaktab.settings
    depends_on:
      - db  # Ensure 'db' service starts before 'web'

volumes:
  postgres_data:
  static_volume:
  media_volume: