# Generated by Django 5.0.6 on 2024-09-17 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=255, verbose_name='Familiya')),
                ('grade', models.PositiveSmallIntegerField(verbose_name='Sinf')),
                ('id_unique', models.CharField(default='1ZQ57C', max_length=255, unique=True, verbose_name="O'quvchi ID")),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_questions', models.PositiveSmallIntegerField(verbose_name='Savollar soni')),
                ('result', models.PositiveSmallIntegerField(verbose_name='Natija')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseIT.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Natija',
                'verbose_name_plural': 'Natijalar',
            },
        ),
    ]
