# Generated by Django 5.0.6 on 2024-09-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseIT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='month',
            field=models.CharField(default='Sentabr', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_unique',
            field=models.CharField(default='9KI53R', max_length=255, unique=True, verbose_name="O'quvchi ID"),
        ),
    ]
