# Generated by Django 5.0.6 on 2024-09-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseIT', '0002_studentresult_month_alter_student_id_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id_unique',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='month',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Gruh raqami'),
        ),
    ]
