# Generated by Django 5.0.6 on 2024-08-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olimpiada25082024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='F.I.Sh')),
                ('grade', models.CharField(max_length=255, verbose_name='Sinf')),
                ('phone', models.CharField(max_length=255, verbose_name='Tel')),
                ('telegram_id', models.CharField(max_length=255, verbose_name='Telegram_id')),
            ],
            options={
                'verbose_name': 'Olimpiada 25.08.2024',
                'verbose_name_plural': 'Olimpiada 25.08.2024',
            },
        ),
    ]
